# Informações básicas do site
title: Prof. Dr. Francisco de Assis Nascimento Junior
author: Francisco Nascimento
email: francisco.assis@gfe.ufsb.edu.br
github: itxesco
production_url: https://itxesco.github.io

# URLs mais amigáveis
permalink: pretty

# Interpretador de Markdown e destaque de código
markdown: kramdown
highlighter: rouge

# Arquivos/pastas a serem ignorados na build
exclude:
  - .rvmrc
  - .rbenv-version
  - ReadMe.md
  - Rakefile
  - changelog.md
  - License.md
  - Makefile
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

# Desativar recursos não utilizados (comentários, analytics, compartilhamento)
comments:
  provider: false

analytics:
  provider: false

sharing:
  provider: false
